
import { create } from 'xmlbuilder2';
import type { ClassRoom, Hour } from '../../src/lib/types.js';
import { buildAllConstraints } from './constraints/index.js';
import type { ConstraintNode } from './constraints/index.js';
import type { BuilderContext, SchoolBundle, SkippedConstraint } from './types.js';

const FET_VERSION = '6.8.5';
const MIN_DAYS_WEIGHT = 95;
const PER_DAY_BLOCKED_WEIGHT = 100;
const SPLIT_GROUP_WEIGHT = 100;

export type BuildResult = {
  xml: string;
  skipped: SkippedConstraint[];
  fetActivityIdsByActivity: Map<number, number[]>;
  activityGroupIdById: Map<number, number>;
};

export function buildFetXml(school: SchoolBundle): BuildResult {
  const ctx = buildContext(school);

  const { time: timeNodes, space: spaceNodes } = buildAllConstraints(school.constraints, ctx);

  prependBasicConstraints(timeNodes, spaceNodes);
  appendMinDaysBetweenActivities(timeNodes, ctx);
  appendShortDayBlockedSlots(timeNodes, ctx);
  appendSplitGroupConstraints(timeNodes, ctx);

  const doc = create({ version: '1.0', encoding: 'UTF-8' });
  const root = doc.ele('fet', { version: FET_VERSION });

  root.ele('Institution_Name').txt(school.institutionName || 'Okul').up();
  root.ele('Comments').txt('Generated by Ders Program Oluşturucu — ÖğretimSayfam').up();

  buildDaysList(root, ctx);
  buildHoursList(root, ctx);
  buildSubjectsList(root, ctx);
  buildTeachersList(root, ctx);
  buildStudentsList(root, ctx);
  buildActivitiesList(root, ctx);
  buildBuildingsList(root);
  buildRoomsList(root, ctx);
  buildConstraintList(root, 'Time_Constraints_List', timeNodes);
  buildConstraintList(root, 'Space_Constraints_List', spaceNodes);

  const xml = doc.end({ prettyPrint: true });

  return {
    xml,
    skipped: ctx.skipped,
    fetActivityIdsByActivity: ctx.fetActivityIdsByActivity,
    activityGroupIdById: ctx.activityGroupIdById,
  };
}


function buildContext(school: SchoolBundle): BuilderContext {
  const days = [...school.days].sort((a, b) => a.orderIndex - b.orderIndex);
  const globalHours = [...school.hours].sort((a, b) => a.orderIndex - b.orderIndex);

  const dayHoursByDay = new Map<number, NonNullable<SchoolBundle['dayHours']>>();
  for (const dh of school.dayHours ?? []) {
    const arr = dayHoursByDay.get(dh.dayId) ?? [];
    arr.push(dh);
    dayHoursByDay.set(dh.dayId, arr);
  }
  for (const [k, arr] of dayHoursByDay) {
    arr.sort((a, b) => a.orderIndex - b.orderIndex);
    dayHoursByDay.set(k, arr);
  }

  const effectiveHoursPerDay = new Map<number, number>();
  for (const d of days) {
    const override = dayHoursByDay.get(d.id);
    const count = override && override.length > 0 ? override.length : globalHours.length;
    effectiveHoursPerDay.set(d.id, count);
  }

  const maxHours = Math.max(globalHours.length, ...effectiveHoursPerDay.values(), 1);
  const hours: Hour[] = [];
  for (let i = 0; i < maxHours; i++) {
    const g = globalHours[i];
    if (g) {
      hours.push(g);
      continue;
    }
    let label = `${i + 1}. Ders`;
    for (const arr of dayHoursByDay.values()) {
      const h = arr[i];
      if (h && h.name) {
        label = h.name;
        break;
      }
    }
    hours.push({ id: -(i + 1), name: label, orderIndex: i, startTime: null, endTime: null });
  }

  const dayByName = new Map(days.map(d => [d.name, d]));
  // hourByOrder: 1-indexed (Plans/05 Slot.hour 1..N)
  const hourByOrder = new Map<number, typeof hours[number]>();
  hours.forEach((h, idx) => hourByOrder.set(idx + 1, h));

  const teacherByName = new Map(school.teachers.map(t => [t.name, t]));
  const classByName = new Map(school.classes.map(c => [c.name, c]));
  const subjectByName = new Map(school.subjects.map(s => [s.name, s]));
  const roomByName = new Map(school.rooms.map(r => [r.name, r]));

  // FET Activity Id'leri 1'den başlayarak global olarak artar.
  // Bir DB activity → blocks adet FET Activity üretir.
  //   blocks = ceil(weeklyHours / blockDuration); her birinin Duration = blockDuration
  //   (son blok kalan saat kadar olabilir)
  const fetActivityIdsByActivity = new Map<number, number[]>();
  const activityGroupIdById = new Map<number, number>();
  let nextId = 1;
  let nextGroup = 1;
  for (const a of school.activities) {
    const block = Math.max(1, a.blockDuration || 1);
    const total = Math.max(1, a.weeklyHours || 1);
    // Sayı hesabı: tamsayı bölümle blok sayısı + kalan
    const fullBlocks = Math.floor(total / block);
    const remainder = total - fullBlocks * block;
    const count = fullBlocks + (remainder > 0 ? 1 : 0);
    const ids: number[] = [];
    for (let i = 0; i < count; i++) ids.push(nextId++);
    fetActivityIdsByActivity.set(a.id, ids);
    activityGroupIdById.set(a.id, nextGroup++);
  }

  const activityGroupBySubjectClass = new Map<string, number>();
  for (const a of school.activities) {
    const key = `${a.subjectId}:${a.classId}`;
    const gid = activityGroupIdById.get(a.id);
    if (gid !== undefined) activityGroupBySubjectClass.set(key, gid);
  }

  // Split-aware subgroup atama:
  //  - "Split group" = aynı splitGroupId'yi paylaşan aktivitelerin oluşturduğu küme.
  //    Bu küme aynı saatte koşacak (FET'te ConstraintActivitiesSameStartingTime).
  //  - Aynı saatte koşacaklar için her birinin farklı bir Subgroup'a düşmesi şart
  //    (yoksa FET çakışma sayar).
  //  - Bir sınıf birden fazla split_group'a katılabilir. Her split_group içinde
  //    iki/üç aktivite varsa "parallelism = 2/3". Sınıfın kaç subgroup'a bölündüğü
  //    en yüksek parallelism kadar.
  //  - Tek bir split_group içinde aktivite sırası, sınıf-subgroup eşlemesini belirler:
  //      i. aktivite → "<class>_g{i+1}". Farklı split_grup'lar arası tutarlılık şart değil.
  const classById = new Map(school.classes.map(c => [c.id, c]));
  const splitGroupsByClass = new Map<number, Map<number, number[]>>();
  // classId → Map(splitGroupId → ordered activity ids)
  for (const a of school.activities) {
    if (a.splitGroupId == null) continue;
    const cmap = splitGroupsByClass.get(a.classId) ?? new Map<number, number[]>();
    const arr = cmap.get(a.splitGroupId) ?? [];
    arr.push(a.id);
    cmap.set(a.splitGroupId, arr);
    splitGroupsByClass.set(a.classId, cmap);
  }

  // Her sınıf için kaç subgroup gerekecek?
  const subgroupCountByClass = new Map<number, number>();
  for (const [classId, cmap] of splitGroupsByClass) {
    let maxN = 0;
    for (const [, arr] of cmap) maxN = Math.max(maxN, arr.length);
    subgroupCountByClass.set(classId, maxN);
  }

  const studentsNameByActivity = new Map<number, string>();
  for (const a of school.activities) {
    const cls = classById.get(a.classId);
    if (!cls) continue;
    if (a.splitGroupId == null) {
      studentsNameByActivity.set(a.id, cls.name);
      continue;
    }
    const cmap = splitGroupsByClass.get(a.classId);
    const arr = cmap?.get(a.splitGroupId) ?? [];
    const idx = arr.indexOf(a.id);
    if (idx < 0) {
      studentsNameByActivity.set(a.id, cls.name);
      continue;
    }
    studentsNameByActivity.set(a.id, `${cls.name}_g${idx + 1}`);
  }

  return {
    days,
    hours,
    dayByName,
    hourByOrder,
    effectiveHoursPerDay,
    teachers: school.teachers,
    teacherByName,
    classes: school.classes,
    classByName,
    subjects: school.subjects,
    subjectByName,
    rooms: school.rooms,
    roomByName,
    activities: school.activities,
    activityGroupIdById,
    activityGroupBySubjectClass,
    fetActivityIdsByActivity,
    studentsNameByActivity,
    skipped: [],
  };
}

/**
 * Sınıfta kaç tane subgroup gerekiyor? = herhangi bir split_group içindeki
 * en kalabalık aktivite kümesinin boyutu (paralellik derecesi).
 * Split yoksa 0 → tek default subgroup yazılır.
 */
function splitSubgroupCountByClass(ctx: BuilderContext): Map<number, number> {
  // classId → splitGroupId → activity sayısı
  const counts = new Map<number, Map<number, number>>();
  for (const a of ctx.activities) {
    if (a.splitGroupId == null) continue;
    const cmap = counts.get(a.classId) ?? new Map<number, number>();
    cmap.set(a.splitGroupId, (cmap.get(a.splitGroupId) ?? 0) + 1);
    counts.set(a.classId, cmap);
  }
  const out = new Map<number, number>();
  for (const [cid, cmap] of counts) {
    let mx = 0;
    for (const [, n] of cmap) mx = Math.max(mx, n);
    out.set(cid, mx);
  }
  return out;
}

// ---------- liste builder'ları ----------

type XmlNode = ReturnType<ReturnType<typeof create>['ele']>;

function buildDaysList(root: XmlNode, ctx: BuilderContext): void {
  const list = root.ele('Days_List');
  list.ele('Number_of_Days').txt(String(ctx.days.length)).up();
  for (const d of ctx.days) {
    list.ele('Day').ele('Name').txt(d.name).up().up();
  }
}

function buildHoursList(root: XmlNode, ctx: BuilderContext): void {
  const list = root.ele('Hours_List');
  list.ele('Number_of_Hours').txt(String(ctx.hours.length)).up();
  for (const h of ctx.hours) {
    list.ele('Hour').ele('Name').txt(h.name).up().up();
  }
}

function buildSubjectsList(root: XmlNode, ctx: BuilderContext): void {
  const list = root.ele('Subjects_List');
  for (const s of ctx.subjects) {
    const node = list.ele('Subject');
    node.ele('Name').txt(s.name).up();
    node.ele('Comments').txt(s.notes ?? '').up();
    node.up();
  }
}

function buildTeachersList(root: XmlNode, ctx: BuilderContext): void {
  const list = root.ele('Teachers_List');
  for (const t of ctx.teachers) {
    const node = list.ele('Teacher');
    node.ele('Name').txt(t.name).up();
    node.ele('Target_Number_of_Hours').txt(String(t.weeklyTargetHours ?? 0)).up();
    const qual = node.ele('Qualified_Subjects');
    if (t.subjectIds && t.subjectIds.length > 0) {
      const subjMap = new Map(ctx.subjects.map(s => [s.id, s.name]));
      for (const sid of t.subjectIds) {
        const sname = subjMap.get(sid);
        if (sname) qual.ele('Qualified_Subject').txt(sname).up();
      }
    }
    qual.up();
    node.ele('Comments').txt(t.notes ?? '').up();
    node.up();
  }
}

/**
 * Students_List üretir. Her sınıfı kendi Year > Group > Subgroup üçlüsüne koyar.
 *
 * Neden böyle? FET 6.x'te:
 *  - Year > Group > Subgroup hiyerarşisi zorunlu (Activity'ler Subgroup'a atanır).
 *  - Sınıflar bizim modelde alt-gruplara bölünmüyor, dolayısıyla tek Subgroup yeterli.
 *  - Aynı yearId'ye sahip sınıfları tek <Year> altında toplamak FET için
 *    şart değil — ayrı Year'lar verdiğimizde de tüm constraint'ler düzgün çalışır.
 *
 * Year ismini "Y_<sınıf>" yapıyoruz çünkü FET Year/Group/Subgroup isimlerinin
 * benzersiz olmasını ister.
 */
function buildStudentsList(root: XmlNode, ctx: BuilderContext): void {
  const list = root.ele('Students_List');
  const subgroupCount = splitSubgroupCountByClass(ctx);
  for (const c of ctx.classes) {
    writeYearGroupSubgroupForClass(list, c, subgroupCount.get(c.id) ?? 0);
  }
  list.up();
}

/**
 * Bir sınıf için Year/Group/Subgroup üçlüsünü yazar.
 *
 * FET 6.x zorunluluğu: Year, Group ve Subgroup isimleri farklı olmalı —
 * aynı isimli iki seviyeyi FET reddediyor ("subgroup X already added as another group").
 * Bu yüzden:
 *  - Year   = "Y_<class>"
 *  - Group  = "<class>"           ← non-split activity'lerdeki <Students> bu adı referans alır
 *  - Subgroup'lar:
 *      - Split yoksa: tek "<class>_s" (default — eski davranış)
 *      - Split varsa: her unique split_group_id için bir subgroup "<class>_g1", "<class>_g2", …
 *        Default "_s" YERİNE bunlar yazılır; çünkü FET'te bir Group, kendi
 *        subgroup'larının BİRLEŞİMİ değildir ve non-split aktiviteler Group adına
 *        atandığında otomatik olarak tüm subgroup'ları kapsar (aynı sınıfın
 *        diğer dersleri zaten Group seviyesinden çakışmayı engelleniyor).
 */
function writeYearGroupSubgroupForClass(
  parent: XmlNode,
  c: ClassRoom,
  parallelCount: number,
): void {
  const year = parent.ele('Year');
  year.ele('Name').txt(`Y_${c.name}`).up();
  year.ele('Number_of_Students').txt(String(c.studentCount ?? 0)).up();
  const group = year.ele('Group');
  group.ele('Name').txt(c.name).up();
  group.ele('Number_of_Students').txt(String(c.studentCount ?? 0)).up();

  if (parallelCount <= 1) {
    const sub = group.ele('Subgroup');
    sub.ele('Name').txt(`${c.name}_s`).up();
    sub.ele('Number_of_Students').txt(String(c.studentCount ?? 0)).up();
    sub.up();
  } else {
    // parallelCount kadar subgroup yaratılır. Her birine öğrenci sayısı yaklaşık eşit dağıtılır.
    const total = c.studentCount ?? 0;
    const base = Math.floor(total / parallelCount);
    const remainder = total - base * parallelCount;
    for (let i = 0; i < parallelCount; i++) {
      const sub = group.ele('Subgroup');
      sub.ele('Name').txt(`${c.name}_g${i + 1}`).up();
      const count = base + (i < remainder ? 1 : 0);
      sub.ele('Number_of_Students').txt(String(count)).up();
      sub.up();
    }
  }
  group.up();
  year.up();
}

function buildActivitiesList(root: XmlNode, ctx: BuilderContext): void {
  const list = root.ele('Activities_List');
  const subjMap = new Map(ctx.subjects.map(s => [s.id, s.name]));
  const teacherMap = new Map(ctx.teachers.map(t => [t.id, t.name]));
  const classMap = new Map(ctx.classes.map(c => [c.id, c.name]));

  for (const a of ctx.activities) {
    const block = Math.max(1, a.blockDuration || 1);
    const total = Math.max(1, a.weeklyHours || 1);
    const groupId = ctx.activityGroupIdById.get(a.id);
    const fetIds = ctx.fetActivityIdsByActivity.get(a.id) ?? [];
    if (!groupId || fetIds.length === 0) continue;

    const subjectName = subjMap.get(a.subjectId) ?? '';
    const teacherName = a.teacherId != null ? teacherMap.get(a.teacherId) : null;
    const studentsName =
      ctx.studentsNameByActivity.get(a.id) ?? classMap.get(a.classId) ?? '';

    // Her FET Activity'nin Duration'ı: son haricinde block, kalan varsa son = remainder
    const fullBlocks = Math.floor(total / block);
    const remainder = total - fullBlocks * block;
    for (let i = 0; i < fetIds.length; i++) {
      const isLastWithRemainder = remainder > 0 && i === fetIds.length - 1;
      const duration = isLastWithRemainder ? remainder : block;

      const act = list.ele('Activity');
      if (teacherName) act.ele('Teacher').txt(teacherName).up();
      act.ele('Subject').txt(subjectName).up();
      act.ele('Students').txt(studentsName).up();
      act.ele('Duration').txt(String(duration)).up();
      act.ele('Total_Duration').txt(String(total)).up();
      act.ele('Id').txt(String(fetIds[i])).up();
      act.ele('Activity_Group_Id').txt(String(groupId)).up();
      act.ele('Active').txt('true').up();
      act.ele('Comments').txt(a.notes ?? '').up();
      act.up();
    }
  }
}

function buildBuildingsList(root: XmlNode): void {
  root.ele('Buildings_List').up();
}

function buildRoomsList(root: XmlNode, ctx: BuilderContext): void {
  const list = root.ele('Rooms_List');
  for (const r of ctx.rooms) {
    const node = list.ele('Room');
    node.ele('Name').txt(r.name).up();
    node.ele('Building').txt(r.building ?? '').up();
    node.ele('Capacity').txt(String(r.capacity ?? 0)).up();
    node.ele('Virtual').txt('false').up();
    node.ele('Comments').txt(r.notes ?? '').up();
    node.up();
  }
}

// ---------- constraint listeleri ----------

function prependBasicConstraints(
  timeNodes: ConstraintNode[],
  spaceNodes: ConstraintNode[],
): void {
  timeNodes.unshift({
    section: 'time',
    tag: 'ConstraintBasicCompulsoryTime',
    body: { Weight_Percentage: 100, Active: true, Comments: '' },
  });
  spaceNodes.unshift({
    section: 'space',
    tag: 'ConstraintBasicCompulsorySpace',
    body: { Weight_Percentage: 100, Active: true, Comments: '' },
  });
}

function appendMinDaysBetweenActivities(
  timeNodes: ConstraintNode[],
  ctx: BuilderContext,
): void {
  for (const [, fetIds] of ctx.fetActivityIdsByActivity) {
    if (fetIds.length < 2) continue; // tek aktivite için anlamsız
    timeNodes.push({
      section: 'time',
      tag: 'ConstraintMinDaysBetweenActivities',
      body: {
        Weight_Percentage: MIN_DAYS_WEIGHT,
        Consecutive_If_Same_Day: true,
        Number_of_Activities: fetIds.length,
        Activity_Id: fetIds,
        MinDays: 1,
        Active: true,
        Comments: '',
      },
    });
  }
}

/**
 * Per-day hours desteği: en uzun gün baz alınarak Hours_List üretilir.
 * Kısa günlerde fazla saatleri TÜM öğretmen ve sınıf için
 * "not available" olarak işaretle — böylece FET o slot'lara aktivite yerleştirmez.
 *
 * Örnek: global 8 saat, Cuma 7 → 8. saat Cuma için kapalı.
 *
 * Not: Tek bir global ConstraintBreakTimes node'u yeterli olabilirdi ama
 * FET'in bazı sürümlerinde "all subgroups" davranışı garanti değil; bu
 * yüzden hem teacher hem students set bazında kapatıyoruz (idempotent ve
 * güvenli yaklaşım).
 */
function appendShortDayBlockedSlots(
  timeNodes: ConstraintNode[],
  ctx: BuilderContext,
): void {
  const totalHours = ctx.hours.length;
  // (day, hour) çiftlerini topla — bunlar tüm okulda kapatılacak.
  const blocked: { Day: string; Hour: string }[] = [];
  for (const d of ctx.days) {
    const eff = ctx.effectiveHoursPerDay.get(d.id) ?? totalHours;
    if (eff >= totalHours) continue;
    for (let i = eff; i < totalHours; i++) {
      const h = ctx.hours[i];
      if (!h) continue;
      blocked.push({ Day: d.name, Hour: h.name });
    }
  }
  if (blocked.length === 0) return;

  // FET'te ConstraintBreakTimes "okul geneli teneffüs/kapalı saat" anlamı taşır:
  // hiçbir aktivite (öğretmen/sınıf/oda) o slot'a yerleştirilmez. Bu, hem
  // öğretmen hem sınıf için "not available" yazmaktan daha temiz ve hızlı.
  timeNodes.push({
    section: 'time',
    tag: 'ConstraintBreakTimes',
    body: {
      Weight_Percentage: PER_DAY_BLOCKED_WEIGHT,
      Number_of_Break_Times: blocked.length,
      Break_Time: blocked,
      Active: true,
      Comments: 'Per-day kısa gün boş saatleri (auto)',
    },
  });
}

/**
 * Split activities: aynı split_group_id'ye sahip aktivitelerin ilk FET
 * Activity'leri aynı saatte başlamaya zorlanır
 * (ConstraintActivitiesSameStartingTime).
 *
 * Önemli detay: bir DB activity birden fazla FET Activity'ye expand
 * olabilir (örn. haftalık 4 saat). Split group'ta iki aktiviteyi sadece
 * aktivitelerin "i. tekrarı" düzeyinde eşliyoruz — yani her tekrar için
 * ayrı ConstraintActivitiesSameStartingTime. Tekrar sayıları farklıysa
 * ortak minimum kadarıyla sınırlıyoruz (geri kalan tekrarlar serbest).
 */
function appendSplitGroupConstraints(
  timeNodes: ConstraintNode[],
  ctx: BuilderContext,
): void {
  const groups = new Map<number, number[]>(); // groupId → activity DB id'leri
  for (const a of ctx.activities) {
    if (a.splitGroupId == null) continue;
    const arr = groups.get(a.splitGroupId) ?? [];
    arr.push(a.id);
    groups.set(a.splitGroupId, arr);
  }

  for (const [, dbIds] of groups) {
    if (dbIds.length < 2) continue;
    // Her DB activity için FET Id listesi
    const fetIdLists = dbIds
      .map(id => ctx.fetActivityIdsByActivity.get(id) ?? [])
      .filter(list => list.length > 0);
    if (fetIdLists.length < 2) continue;

    const minLen = Math.min(...fetIdLists.map(l => l.length));
    for (let i = 0; i < minLen; i++) {
      const sameSlotIds = fetIdLists.map(l => l[i]!);
      timeNodes.push({
        section: 'time',
        tag: 'ConstraintActivitiesSameStartingTime',
        body: {
          Weight_Percentage: SPLIT_GROUP_WEIGHT,
          Number_of_Activities: sameSlotIds.length,
          Activity_Id: sameSlotIds,
          Active: true,
          Comments: 'Split group (auto)',
        },
      });
    }
  }
}

function buildConstraintList(
  root: XmlNode,
  listTag: string,
  nodes: ConstraintNode[],
): void {
  const list = root.ele(listTag);
  for (const n of nodes) {
    const wrap = list.ele(n.tag);
    writeBody(wrap, n.body);
    wrap.up();
  }
  list.up();
}

function writeBody(parent: XmlNode, body: Record<string, unknown>): void {
  for (const [key, raw] of Object.entries(body)) {
    if (raw === undefined || raw === null) continue;

    if (Array.isArray(raw)) {
      for (const item of raw) {
        if (item === undefined || item === null) continue;
        if (typeof item === 'object') {
          const child = parent.ele(key);
          writeBody(child, item as Record<string, unknown>);
          child.up();
        } else {
          parent.ele(key).txt(String(item)).up();
        }
      }
      continue;
    }

    if (typeof raw === 'object') {
      const child = parent.ele(key);
      writeBody(child, raw as Record<string, unknown>);
      child.up();
      continue;
    }

    parent.ele(key).txt(String(raw)).up();
  }
}
